#!/bin/sh

# EST shared script

extend() {
	var="$1"
	extra="$2"
	eval "val=\$$var"
	
	if [ -n "$val" ]
		then
		val="$extra:$val"
	else
		val="$extra"
	fi
	eval "$var='$val'"
	eval "export $var"
	}

extend __LDVAR__ "__LIB__:__LDPATH__"

exec __MAIN__/__PROGRAM__ "$@"

exit 0

